USE ROLE SYSADMIN;
USE WAREHOUSE SUPPLIER_TRANSFORM_WH;
USE DATABASE SUPPLIER_DW;

CREATE SCHEMA IF NOT EXISTS SILVER;

-- 1) Clean current-state Silver table
CREATE OR REPLACE TABLE SUPPLIER_DW.SILVER.SUPPLIERS_CLEAN (
    SUPPLIER_ID             VARCHAR(50)    NOT NULL,
    SUPPLIER_NAME           VARCHAR(255),
    COUNTRY_CODE            VARCHAR(10),
    REGION                  VARCHAR(100),
    CATEGORY                VARCHAR(100),
    CONTRACT_VALUE_USD      NUMBER(18,2),
    LEAD_TIME_DAYS          INTEGER,
    QUALITY_SCORE           NUMBER(5,2),
    ON_TIME_DELIVERY_PCT    NUMBER(5,2),
    RISK_RATING             VARCHAR(50),
    LAST_AUDIT_DATE         DATE,
    IS_ACTIVE               BOOLEAN,
    SOURCE_FILE_NAME        VARCHAR(500),
    SOURCE_ROW_NUMBER       NUMBER,
    LOAD_TS                 TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    RECORD_HASH             VARCHAR(64),
    CONSTRAINT PK_SUPPLIERS_CLEAN PRIMARY KEY (SUPPLIER_ID)
);

-- 2) Historical SCD Type 2 dimension
CREATE OR REPLACE TABLE SUPPLIER_DW.SILVER.DIM_SUPPLIERS (
    SUPPLIER_SK             NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    SUPPLIER_ID             VARCHAR(50)    NOT NULL,
    SUPPLIER_NAME           VARCHAR(255),
    COUNTRY_CODE            VARCHAR(10),
    REGION                  VARCHAR(100),
    CATEGORY                VARCHAR(100),
    CONTRACT_VALUE_USD      NUMBER(18,2),
    LEAD_TIME_DAYS          INTEGER,
    QUALITY_SCORE           NUMBER(5,2),
    ON_TIME_DELIVERY_PCT    NUMBER(5,2),
    RISK_RATING             VARCHAR(50),
    LAST_AUDIT_DATE         DATE,
    IS_ACTIVE               BOOLEAN,
    DQ_PASSED               BOOLEAN DEFAULT TRUE,
    DQ_FAIL_REASONS         VARCHAR(1000),
    RECORD_HASH             VARCHAR(64),
    VALID_FROM              TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    VALID_TO                TIMESTAMP_NTZ,
    IS_CURRENT              BOOLEAN DEFAULT TRUE,
    SOURCE_FILE_NAME        VARCHAR(500),
    SOURCE_ROW_NUMBER       NUMBER,
    LOAD_TS                 TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_DIM_SUPPLIERS PRIMARY KEY (SUPPLIER_SK)
);

-- 3) Rejected / failed records table
CREATE OR REPLACE TABLE SUPPLIER_DW.SILVER.REJECTED_SUPPLIERS (
    REJECT_ID               NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    SUPPLIER_ID             VARCHAR(50),
    SUPPLIER_NAME           VARCHAR(255),
    COUNTRY_CODE            VARCHAR(10),
    REGION                  VARCHAR(100),
    CATEGORY                VARCHAR(100),
    CONTRACT_VALUE_USD      NUMBER(18,2),
    LEAD_TIME_DAYS          INTEGER,
    QUALITY_SCORE           NUMBER(5,2),
    ON_TIME_DELIVERY_PCT    NUMBER(5,2),
    RISK_RATING             VARCHAR(50),
    LAST_AUDIT_DATE         DATE,
    IS_ACTIVE               BOOLEAN,
    REJECTION_REASON        VARCHAR(1000),
    SOURCE_FILE_NAME        VARCHAR(500),
    SOURCE_ROW_NUMBER       NUMBER,
    REJECTED_TS             TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_REJECTED_SUPPLIERS PRIMARY KEY (REJECT_ID)
);

-- 4) Optional helper stream on Bronze raw table for incremental processing
CREATE OR REPLACE STREAM SUPPLIER_DW.BRONZE.STR_RAW_SUPPLIERS
ON TABLE SUPPLIER_DW.BRONZE.RAW_SUPPLIERS;

-- 5) Helpful clustering hint for historical lookups
ALTER TABLE SUPPLIER_DW.SILVER.DIM_SUPPLIERS
CLUSTER BY (SUPPLIER_ID, IS_CURRENT);

-- 6) Comments
COMMENT ON TABLE SUPPLIER_DW.SILVER.SUPPLIERS_CLEAN IS
'Silver cleaned current-state supplier table derived from Bronze raw supplier feed.';

COMMENT ON TABLE SUPPLIER_DW.SILVER.DIM_SUPPLIERS IS
'Silver SCD Type 2 supplier dimension with historical tracking and DQ flags.';

COMMENT ON TABLE SUPPLIER_DW.SILVER.REJECTED_SUPPLIERS IS
'Silver rejected supplier rows that failed validation or transformation rules.';

COMMENT ON STREAM SUPPLIER_DW.BRONZE.STR_RAW_SUPPLIERS IS
'CDC stream on Bronze raw supplier table for incremental Silver processing.';