USE ROLE ACCOUNTADMIN;
USE DATABASE SUPPLIER_DW;

-- ============================================================
-- FILE: 10_rbac_setup.sql
-- PURPOSE: Role-Based Access Control (RBAC)
--   4 custom roles with least-privilege access:
--   - SUPPLIER_INGEST_ROLE: Snowpipe + Bronze writes
--   - SUPPLIER_TRANSFORM_ROLE: Procedures, tasks, Silver/Gold writes
--   - SUPPLIER_ANALYST_ROLE: Read-only on Gold + Audit
--   - SUPPLIER_STREAMLIT_ROLE: Read-only for dashboard app
-- ============================================================

-- =============================================================
-- 1) CREATE ROLES
-- =============================================================
CREATE ROLE IF NOT EXISTS SUPPLIER_INGEST_ROLE
    COMMENT = 'Ingestion role for Snowpipe and Bronze layer writes';
CREATE ROLE IF NOT EXISTS SUPPLIER_TRANSFORM_ROLE
    COMMENT = 'Transform role for procedures, tasks, and Silver/Gold writes';
CREATE ROLE IF NOT EXISTS SUPPLIER_ANALYST_ROLE
    COMMENT = 'Analyst role with read-only access to Gold and Audit';
CREATE ROLE IF NOT EXISTS SUPPLIER_STREAMLIT_ROLE
    COMMENT = 'Streamlit dashboard role with read-only access';

-- =============================================================
-- 2) ROLE HIERARCHY (best practice: chain up to SYSADMIN)
-- =============================================================
GRANT ROLE SUPPLIER_INGEST_ROLE TO ROLE SYSADMIN;
GRANT ROLE SUPPLIER_TRANSFORM_ROLE TO ROLE SYSADMIN;
GRANT ROLE SUPPLIER_ANALYST_ROLE TO ROLE SYSADMIN;
GRANT ROLE SUPPLIER_STREAMLIT_ROLE TO ROLE SYSADMIN;

-- Analyst inherits Streamlit access
GRANT ROLE SUPPLIER_STREAMLIT_ROLE TO ROLE SUPPLIER_ANALYST_ROLE;

-- =============================================================
-- 3) WAREHOUSE GRANTS
-- =============================================================
GRANT USAGE, OPERATE ON WAREHOUSE SUPPLIER_INGEST_WH TO ROLE SUPPLIER_INGEST_ROLE;
GRANT USAGE, OPERATE ON WAREHOUSE SUPPLIER_TRANSFORM_WH TO ROLE SUPPLIER_TRANSFORM_ROLE;
GRANT USAGE ON WAREHOUSE SUPPLIER_ANALYTICS_WH TO ROLE SUPPLIER_ANALYST_ROLE;
GRANT USAGE ON WAREHOUSE SUPPLIER_ANALYTICS_WH TO ROLE SUPPLIER_STREAMLIT_ROLE;

-- =============================================================
-- 4) DATABASE + SCHEMA USAGE
-- =============================================================
GRANT USAGE ON DATABASE SUPPLIER_DW TO ROLE SUPPLIER_INGEST_ROLE;
GRANT USAGE ON DATABASE SUPPLIER_DW TO ROLE SUPPLIER_TRANSFORM_ROLE;
GRANT USAGE ON DATABASE SUPPLIER_DW TO ROLE SUPPLIER_ANALYST_ROLE;
GRANT USAGE ON DATABASE SUPPLIER_DW TO ROLE SUPPLIER_STREAMLIT_ROLE;

-- Ingest role: Bronze only
GRANT USAGE ON SCHEMA SUPPLIER_DW.BRONZE TO ROLE SUPPLIER_INGEST_ROLE;

-- Transform role: all schemas
GRANT USAGE ON SCHEMA SUPPLIER_DW.BRONZE TO ROLE SUPPLIER_TRANSFORM_ROLE;
GRANT USAGE ON SCHEMA SUPPLIER_DW.SILVER TO ROLE SUPPLIER_TRANSFORM_ROLE;
GRANT USAGE ON SCHEMA SUPPLIER_DW.GOLD TO ROLE SUPPLIER_TRANSFORM_ROLE;
GRANT USAGE ON SCHEMA SUPPLIER_DW.AUDIT TO ROLE SUPPLIER_TRANSFORM_ROLE;

-- Analyst role: Gold + Audit
GRANT USAGE ON SCHEMA SUPPLIER_DW.GOLD TO ROLE SUPPLIER_ANALYST_ROLE;
GRANT USAGE ON SCHEMA SUPPLIER_DW.AUDIT TO ROLE SUPPLIER_ANALYST_ROLE;

-- Streamlit role: Gold + Audit
GRANT USAGE ON SCHEMA SUPPLIER_DW.GOLD TO ROLE SUPPLIER_STREAMLIT_ROLE;
GRANT USAGE ON SCHEMA SUPPLIER_DW.AUDIT TO ROLE SUPPLIER_STREAMLIT_ROLE;

-- =============================================================
-- 5) TABLE + VIEW GRANTS
-- =============================================================

-- Bronze: Ingest can write, Transform can read
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA SUPPLIER_DW.BRONZE TO ROLE SUPPLIER_INGEST_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA SUPPLIER_DW.BRONZE TO ROLE SUPPLIER_INGEST_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA SUPPLIER_DW.BRONZE TO ROLE SUPPLIER_TRANSFORM_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SUPPLIER_DW.BRONZE TO ROLE SUPPLIER_TRANSFORM_ROLE;

-- Silver: Transform can read/write
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA SUPPLIER_DW.SILVER TO ROLE SUPPLIER_TRANSFORM_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA SUPPLIER_DW.SILVER TO ROLE SUPPLIER_TRANSFORM_ROLE;

-- Gold: Transform can write, Analyst + Streamlit can read
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA SUPPLIER_DW.GOLD TO ROLE SUPPLIER_TRANSFORM_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA SUPPLIER_DW.GOLD TO ROLE SUPPLIER_TRANSFORM_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA SUPPLIER_DW.GOLD TO ROLE SUPPLIER_ANALYST_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SUPPLIER_DW.GOLD TO ROLE SUPPLIER_ANALYST_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA SUPPLIER_DW.GOLD TO ROLE SUPPLIER_STREAMLIT_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SUPPLIER_DW.GOLD TO ROLE SUPPLIER_STREAMLIT_ROLE;

-- Gold VIEWS: Analyst + Streamlit can read
GRANT SELECT ON ALL VIEWS IN SCHEMA SUPPLIER_DW.GOLD TO ROLE SUPPLIER_ANALYST_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA SUPPLIER_DW.GOLD TO ROLE SUPPLIER_ANALYST_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA SUPPLIER_DW.GOLD TO ROLE SUPPLIER_STREAMLIT_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA SUPPLIER_DW.GOLD TO ROLE SUPPLIER_STREAMLIT_ROLE;

-- Audit: Transform can write, Analyst + Streamlit can read
GRANT SELECT, INSERT ON ALL TABLES IN SCHEMA SUPPLIER_DW.AUDIT TO ROLE SUPPLIER_TRANSFORM_ROLE;
GRANT SELECT, INSERT ON FUTURE TABLES IN SCHEMA SUPPLIER_DW.AUDIT TO ROLE SUPPLIER_TRANSFORM_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA SUPPLIER_DW.AUDIT TO ROLE SUPPLIER_ANALYST_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SUPPLIER_DW.AUDIT TO ROLE SUPPLIER_ANALYST_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA SUPPLIER_DW.AUDIT TO ROLE SUPPLIER_STREAMLIT_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SUPPLIER_DW.AUDIT TO ROLE SUPPLIER_STREAMLIT_ROLE;

-- Audit VIEWS
GRANT SELECT ON ALL VIEWS IN SCHEMA SUPPLIER_DW.AUDIT TO ROLE SUPPLIER_ANALYST_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA SUPPLIER_DW.AUDIT TO ROLE SUPPLIER_ANALYST_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA SUPPLIER_DW.AUDIT TO ROLE SUPPLIER_STREAMLIT_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA SUPPLIER_DW.AUDIT TO ROLE SUPPLIER_STREAMLIT_ROLE;

-- =============================================================
-- 6) STREAM + PIPE GRANTS
-- =============================================================
GRANT SELECT ON STREAM SUPPLIER_DW.BRONZE.STR_RAW_SUPPLIERS TO ROLE SUPPLIER_TRANSFORM_ROLE;
GRANT MONITOR, OPERATE ON PIPE SUPPLIER_DW.BRONZE.PIPE_RAW_SUPPLIERS TO ROLE SUPPLIER_INGEST_ROLE;

-- =============================================================
-- 7) PROCEDURE GRANTS
-- =============================================================
GRANT USAGE ON PROCEDURE SUPPLIER_DW.SILVER.SP_BRONZE_TO_SILVER() TO ROLE SUPPLIER_TRANSFORM_ROLE;
GRANT USAGE ON PROCEDURE SUPPLIER_DW.GOLD.SP_SILVER_TO_GOLD() TO ROLE SUPPLIER_TRANSFORM_ROLE;

-- =============================================================
-- 8) TASK GRANTS
-- =============================================================
GRANT CREATE TASK ON SCHEMA SUPPLIER_DW.SILVER TO ROLE SUPPLIER_TRANSFORM_ROLE;
GRANT CREATE TASK ON SCHEMA SUPPLIER_DW.GOLD TO ROLE SUPPLIER_TRANSFORM_ROLE;

-- =============================================================
-- 9) ASSIGN ROLES TO USERS (update with your username)
-- =============================================================
-- GRANT ROLE SUPPLIER_INGEST_ROLE TO USER <your_user>;
-- GRANT ROLE SUPPLIER_TRANSFORM_ROLE TO USER <your_user>;
-- GRANT ROLE SUPPLIER_ANALYST_ROLE TO USER <your_user>;
-- GRANT ROLE SUPPLIER_STREAMLIT_ROLE TO USER <your_user>;

-- =============================================================
-- Verification
-- =============================================================
SHOW ROLES LIKE 'SUPPLIER%';
SHOW GRANTS TO ROLE SUPPLIER_INGEST_ROLE;
SHOW GRANTS TO ROLE SUPPLIER_TRANSFORM_ROLE;
SHOW GRANTS TO ROLE SUPPLIER_ANALYST_ROLE;
SHOW GRANTS TO ROLE SUPPLIER_STREAMLIT_ROLE;